(function(){
  const DEFAULT_BRANCHES=[
    {code:'CIVIL',name:'Civil Engineering',status:'Active'},
    {code:'CSE',name:'Computer Science and Engineering',status:'Active'},
    {code:'ECE',name:'Electronics and Communication Engineering',status:'Active'},
    {code:'EEE',name:'Electrical and Electronics Engineering',status:'Active'},
    {code:'MECH',name:'Mechanical Engineering',status:'Active'}
  ];
  const DEFAULT_SEMESTERS=[
    {label:'I-I',year:'I',sem:'I',status:'Active'},{label:'I-II',year:'I',sem:'II',status:'Active'},
    {label:'II-I',year:'II',sem:'I',status:'Active'},{label:'II-II',year:'II',sem:'II',status:'Active'},
    {label:'III-I',year:'III',sem:'I',status:'Active'},{label:'III-II',year:'III',sem:'II',status:'Active'},
    {label:'IV-I',year:'IV',sem:'I',status:'Active'},{label:'IV-II',year:'IV',sem:'II',status:'Active'}
  ];
  const YEAR_ORDER=['I','II','III','IV'];
  let subjectRows=[];

  function ensureMasters(){
    if(!Array.isArray(state.branches)||!state.branches.length) state.branches=DEFAULT_BRANCHES.map(x=>({...x}));
    if(!Array.isArray(state.semesters)||!state.semesters.length) state.semesters=DEFAULT_SEMESTERS.map(x=>({...x}));
    saveData();
  }
  function e(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
  function activeBranches(){ensureMasters();return state.branches.filter(x=>(x.status||'Active')==='Active')}
  function activeSemesters(){ensureMasters();return state.semesters.filter(x=>(x.status||'Active')==='Active')}
  function branchOptions(selected='',allLabel=''){const arr=activeBranches();return `${allLabel?`<option value="">${e(allLabel)}</option>`:''}${arr.map(x=>`<option value="${e(x.code)}" ${x.code===selected?'selected':''}>${e(x.code)} — ${e(x.name)}</option>`).join('')}`}
  function semesterOptions(selected='',allLabel=''){const arr=activeSemesters();return `${allLabel?`<option value="">${e(allLabel)}</option>`:''}${arr.map(x=>`<option value="${e(x.label)}" ${x.label===selected?'selected':''}>${e(x.label)}</option>`).join('')}`}
  function showMsg(m){if(typeof toast==='function')toast(m);else alert(m)}

  function injectStyles(){
    if(document.getElementById('academic-module-styles'))return;
    const s=document.createElement('style');s.id='academic-module-styles';s.textContent=`
      .master-grid{display:grid;grid-template-columns:minmax(300px,380px) 1fr;gap:18px;align-items:start}.master-form{display:grid;gap:12px}.master-form label{display:grid;gap:6px;font-size:13px;font-weight:700}.module-badges{display:flex;gap:8px;flex-wrap:wrap}.module-badge{padding:5px 9px;border-radius:999px;background:var(--surface-2);border:1px solid var(--line);font-size:12px;font-weight:800}.subject-bulk-modal{width:min(1080px,96vw)}.subject-preview{max-height:330px;border:1px solid var(--line);border-radius:12px}.subject-preview table{min-width:980px}.dual-ticket-page{display:grid;grid-template-columns:1fr;gap:0}.dual-ticket-half{border:1px solid var(--line);padding:14px;background:#fff;color:#111}.dual-ticket-half+.dual-ticket-half{border-top:2px dashed #777}.dual-ticket-title{text-align:center;margin:0;font-size:17px}.dual-ticket-sub{margin:2px 0 7px;text-align:center;font-size:11px}.dual-ticket-label{text-align:center;font-weight:900;font-size:12px;margin-bottom:8px}.dual-info{width:100%;min-width:0;border-collapse:collapse}.dual-info td{border:1px solid #777;padding:4px 6px;font-size:10px;background:#fff;color:#111}.dual-info td:nth-child(odd){font-weight:700;width:18%}.dual-subjects{width:100%;min-width:0;border-collapse:collapse;margin-top:7px}.dual-subjects th,.dual-subjects td{border:1px solid #777;padding:3px 5px;font-size:9px;background:#fff;color:#111}.dual-sign{display:flex;justify-content:space-between;margin-top:7px;font-size:9px}.hall-note{margin-top:8px;color:var(--muted);font-size:12px}.filter-count{align-self:center;color:var(--muted);font-size:12px;font-weight:700}
      @media(max-width:900px){.master-grid{grid-template-columns:1fr}}
      @media print{.dual-ticket-page{height:270mm;display:grid;grid-template-rows:1fr 1fr}.dual-ticket-half{padding:5mm;border:1px solid #222;overflow:hidden}.dual-ticket-half+.dual-ticket-half{border-top:1px dashed #222}.dual-ticket-title{font-size:15px}.dual-info td{font-size:9px}.dual-subjects th,.dual-subjects td{font-size:8px}.ticket{inset:5mm!important}.ticket .dual-ticket-page{visibility:visible}.ticket .dual-ticket-page *{visibility:visible}}
    `;document.head.appendChild(s);
  }

  function addNavAndViews(){
    const nav=document.querySelector('.nav'),content=document.querySelector('.content');
    if(nav&&!document.querySelector('[data-view="branches"]')){
      const subjectBtn=document.querySelector('[data-view="subjects"]');
      const b=document.createElement('button');b.className='nav-link';b.dataset.view='branches';b.innerHTML='<span>⌘</span>Branches';nav.insertBefore(b,subjectBtn||null);b.addEventListener('click',()=>{navigate('branches');renderBranches()});
      const sm=document.createElement('button');sm.className='nav-link';sm.dataset.view='semesters';sm.innerHTML='<span>◫</span>Semesters';nav.insertBefore(sm,subjectBtn||null);sm.addEventListener('click',()=>{navigate('semesters');renderSemesters()});
    }
    if(content&&!document.getElementById('branches')){
      const sec=document.createElement('section');sec.className='view';sec.id='branches';sec.innerHTML=`<div class="section-toolbar"><div><h3>Branch Master</h3><p>Add and manage branches used in students, subjects and examinations.</p></div></div><div class="master-grid"><div class="card"><h3>Add Branch</h3><form id="branchMasterForm" class="master-form"><label>Branch Code<input class="input" id="branchCode" required placeholder="e.g. AIML"></label><label>Branch Name<input class="input" id="branchName" required placeholder="Artificial Intelligence & Machine Learning"></label><label>Status<select class="input" id="branchStatus"><option>Active</option><option>Inactive</option></select></label><button class="btn btn-primary" type="submit">Save Branch</button></form></div><div class="card"><div class="card-head"><div><h3>Branches</h3><p id="branchCount"></p></div></div><div class="table-wrap"><table><thead><tr><th>Code</th><th>Branch Name</th><th>Students</th><th>Subjects</th><th>Status</th><th></th></tr></thead><tbody id="branchMasterBody"></tbody></table></div></div></div>`;content.appendChild(sec);
      document.getElementById('branchMasterForm').addEventListener('submit',saveBranchFromForm);
    }
    if(content&&!document.getElementById('semesters')){
      const sec=document.createElement('section');sec.className='view';sec.id='semesters';sec.innerHTML=`<div class="section-toolbar"><div><h3>Semester Master</h3><p>Configure semesters for student filtering, subjects and examination processing.</p></div></div><div class="master-grid"><div class="card"><h3>Add Semester</h3><form id="semesterMasterForm" class="master-form"><label>Year<select class="input" id="semesterYear"><option>I</option><option>II</option><option>III</option><option>IV</option></select></label><label>Semester<select class="input" id="semesterPart"><option>I</option><option>II</option></select></label><label>Status<select class="input" id="semesterStatus"><option>Active</option><option>Inactive</option></select></label><button class="btn btn-primary" type="submit">Save Semester</button></form></div><div class="card"><div class="card-head"><div><h3>Semesters</h3><p id="semesterCount"></p></div></div><div class="table-wrap"><table><thead><tr><th>Semester</th><th>Year</th><th>Part</th><th>Subjects</th><th>Status</th><th></th></tr></thead><tbody id="semesterMasterBody"></tbody></table></div></div></div>`;content.appendChild(sec);
      document.getElementById('semesterMasterForm').addEventListener('submit',saveSemesterFromForm);
    }
  }

  function saveBranchFromForm(ev){ev.preventDefault();ensureMasters();const code=document.getElementById('branchCode').value.trim().toUpperCase(),name=document.getElementById('branchName').value.trim(),status=document.getElementById('branchStatus').value;if(!code||!name)return;const found=state.branches.find(x=>x.code===code);if(found){found.name=name;found.status=status}else state.branches.push({code,name,status});saveData();ev.target.reset();refreshAllMasters();showMsg('Branch saved')}
  window.deleteBranchMaster=function(code){ensureMasters();if((state.students||[]).some(s=>s.branch===code)||(state.subjects||[]).some(s=>s.branch===code)){showMsg('Branch is in use. Set it to Inactive instead of deleting.');return}if(confirm(`Delete branch ${code}?`)){state.branches=state.branches.filter(x=>x.code!==code);saveData();refreshAllMasters();showMsg('Branch deleted')}};
  function renderBranches(){ensureMasters();const body=document.getElementById('branchMasterBody');if(!body)return;document.getElementById('branchCount').textContent=`${state.branches.length} branch(es)`;body.innerHTML=state.branches.map(x=>{const sc=(state.students||[]).filter(s=>s.branch===x.code).length,sub=(state.subjects||[]).filter(s=>s.branch===x.code).length;return `<tr><td><b>${e(x.code)}</b></td><td>${e(x.name)}</td><td>${sc}</td><td>${sub}</td><td>${typeof badge==='function'?badge(x.status):e(x.status)}</td><td><button class="table-action danger" onclick="deleteBranchMaster('${e(x.code)}')">Delete</button></td></tr>`}).join('')}

  function saveSemesterFromForm(ev){ev.preventDefault();ensureMasters();const year=document.getElementById('semesterYear').value,sem=document.getElementById('semesterPart').value,status=document.getElementById('semesterStatus').value,label=`${year}-${sem}`,found=state.semesters.find(x=>x.label===label);if(found)found.status=status;else state.semesters.push({label,year,sem,status});state.semesters.sort((a,b)=>YEAR_ORDER.indexOf(a.year)-YEAR_ORDER.indexOf(b.year)||a.sem.localeCompare(b.sem));saveData();refreshAllMasters();showMsg('Semester saved')}
  window.deleteSemesterMaster=function(label){ensureMasters();if((state.subjects||[]).some(s=>s.semester===label)){showMsg('Semester is in use by subjects. Set it to Inactive instead.');return}if(confirm(`Delete semester ${label}?`)){state.semesters=state.semesters.filter(x=>x.label!==label);saveData();refreshAllMasters();showMsg('Semester deleted')}};
  function renderSemesters(){ensureMasters();const body=document.getElementById('semesterMasterBody');if(!body)return;document.getElementById('semesterCount').textContent=`${state.semesters.length} semester(s)`;body.innerHTML=state.semesters.map(x=>{const sub=(state.subjects||[]).filter(s=>s.semester===x.label).length;return `<tr><td><b>${e(x.label)}</b></td><td>${e(x.year)}</td><td>${e(x.sem)}</td><td>${sub}</td><td>${typeof badge==='function'?badge(x.status):e(x.status)}</td><td><button class="table-action danger" onclick="deleteSemesterMaster('${e(x.label)}')">Delete</button></td></tr>`}).join('')}

  function installStudentFilters(){const filters=document.querySelector('#students .filters');if(!filters)return;if(!document.getElementById('yearFilter')){const y=document.createElement('select');y.className='input';y.id='yearFilter';y.innerHTML='<option value="">All Years</option>'+YEAR_ORDER.map(v=>`<option>${v}</option>`).join('');const s=document.createElement('select');s.className='input';s.id='semesterFilter';s.innerHTML='<option value="">All Semesters</option><option>I</option><option>II</option>';const exportBtn=document.getElementById('exportStudentsBtn');filters.insertBefore(y,exportBtn);filters.insertBefore(s,exportBtn);const c=document.createElement('span');c.className='filter-count';c.id='studentFilterCount';filters.insertBefore(c,exportBtn);y.addEventListener('change',renderStudents);s.addEventListener('change',renderStudents)}refreshBranchFilter()}
  function refreshBranchFilter(){const sel=document.getElementById('branchFilter');if(!sel)return;const current=sel.value;sel.innerHTML=branchOptions(current,'All Branches')}
  renderStudents=function(){const q=document.getElementById('studentSearch')?.value.trim().toLowerCase()||'',branch=document.getElementById('branchFilter')?.value||'',year=document.getElementById('yearFilter')?.value||'',sem=document.getElementById('semesterFilter')?.value||'';const items=(state.students||[]).filter(s=>(!q||`${s.hall} ${s.name}`.toLowerCase().includes(q))&&(!branch||s.branch===branch)&&(!year||s.year===year)&&(!sem||s.sem===sem));const body=document.getElementById('studentTableBody');if(body)body.innerHTML=items.map(s=>`<tr><td><b>${e(s.hall)}</b></td><td>${e(s.name)}</td><td>${e(s.branch)}</td><td>${e(s.year)}</td><td>${e(s.sem)}</td><td>${e(s.regulation)}</td><td>${badge(s.status)}</td><td><button class="table-action" onclick="editStudent(${s.id})">Edit</button> <button class="table-action danger" onclick="deleteStudent(${s.id})">Delete</button></td></tr>`).join('')||'<tr><td colspan="8" class="empty-state">No students found.</td></tr>';const c=document.getElementById('studentFilterCount');if(c)c.textContent=`${items.length} / ${(state.students||[]).length} students`};

  const baseOpenStudentModal=openStudentModal;
  openStudentModal=function(s=null){ensureMasters();modalMode={type:'student',id:s?.id||null};openModal(s?'Edit Student':'Add Student',`<div class="form-grid"><label>Hall Ticket No<input class="input" name="hall" required value="${e(s?.hall||'')}"></label><label>Student Name<input class="input" name="name" required value="${e(s?.name||'')}"></label><label>Branch<select class="input" name="branch">${branchOptions(s?.branch||'')}</select></label><label>Year<select class="input" name="year">${YEAR_ORDER.map(x=>`<option ${s?.year===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Semester<select class="input" name="sem"><option ${s?.sem==='I'?'selected':''}>I</option><option ${s?.sem==='II'?'selected':''}>II</option></select></label><label>Regulation<input class="input" name="regulation" value="${e(s?.regulation||state.settings.defaultRegulation)}"></label><label>Status<select class="input" name="status">${['Active','Detained','Completed'].map(x=>`<option ${s?.status===x?'selected':''}>${x}</option>`).join('')}</select></label></div>`)};
  openSubjectModal=function(s=null){ensureMasters();modalMode={type:'subject',id:s?.id||null};openModal(s?'Edit Subject':'Add Subject',`<div class="form-grid"><label>Subject Code<input class="input" name="code" required value="${e(s?.code||'')}"></label><label>Subject Name<input class="input" name="name" required value="${e(s?.name||'')}"></label><label>Branch<select class="input" name="branch">${branchOptions(s?.branch||'')}</select></label><label>Semester<select class="input" name="semester">${semesterOptions(s?.semester||'III-II')}</select></label><label>Credits<input class="input" type="number" min="1" max="10" name="credits" value="${s?.credits||3}"></label><label>Internal Marks<input class="input" type="number" name="internal" value="${s?.internal||30}"></label><label>External Marks<input class="input" type="number" name="external" value="${s?.external||70}"></label></div>`)};

  function installBulkSubject(){const toolbar=document.querySelector('#subjects .section-toolbar');if(!toolbar||document.getElementById('bulkSubjectBtn'))return;const old=toolbar.querySelector('#addSubjectBtn'),wrap=document.createElement('div');wrap.className='button-row toolbar-buttons';const template=document.createElement('button');template.className='btn btn-outline';template.id='downloadSubjectTemplateBtn';template.textContent='Download Template';const bulk=document.createElement('button');bulk.className='btn btn-outline';bulk.id='bulkSubjectBtn';bulk.textContent='Bulk Upload';old.replaceWith(wrap);wrap.append(template,bulk,old);template.addEventListener('click',downloadSubjectTemplate);bulk.addEventListener('click',openSubjectBulkModal);

    const modal=document.createElement('div');modal.className='modal-backdrop';modal.id='subjectBulkBackdrop';modal.hidden=true;modal.innerHTML=`<div class="modal subject-bulk-modal"><div class="modal-head"><div><h3>Bulk Subject Upload</h3><p class="modal-subtitle">Upload CSV or Excel, validate rows and import subjects.</p></div><button class="icon-btn" id="subjectBulkClose">✕</button></div><div class="modal-body"><div class="upload-guide"><div><b>Required columns</b><p>Code, Subject, Branch, Semester, Credits, Internal, External</p></div><button class="btn btn-outline" id="subjectTemplateInside">Download CSV Template</button></div><label class="drop-zone" id="subjectDropZone"><input type="file" id="subjectBulkFile" accept=".csv,.xlsx,.xls" hidden><span class="drop-icon">⇧</span><b>Choose CSV / Excel file</b><small>or drag and drop it here</small></label><div class="bulk-options"><label>Duplicate Subject Code<select class="input" id="subjectDuplicatePolicy"><option value="skip">Skip existing subjects</option><option value="update">Update existing subjects</option></select></label></div><div id="subjectBulkSummary" class="bulk-summary" hidden></div><div id="subjectBulkPreviewWrap" class="bulk-preview-wrap" hidden><div class="table-wrap subject-preview"><table><thead><tr><th>#</th><th>Code</th><th>Subject</th><th>Branch</th><th>Semester</th><th>Credits</th><th>Internal</th><th>External</th><th>Validation</th></tr></thead><tbody id="subjectBulkPreviewBody"></tbody></table></div></div></div><div class="modal-actions"><button class="btn btn-outline" id="subjectBulkCancel">Cancel</button><button class="btn btn-primary" id="subjectImportBtn" disabled>Import Subjects</button></div></div>`;document.body.appendChild(modal);
    document.getElementById('subjectBulkClose').addEventListener('click',closeSubjectBulkModal);document.getElementById('subjectBulkCancel').addEventListener('click',closeSubjectBulkModal);document.getElementById('subjectTemplateInside').addEventListener('click',downloadSubjectTemplate);document.getElementById('subjectDuplicatePolicy').addEventListener('change',renderSubjectBulkPreview);document.getElementById('subjectImportBtn').addEventListener('click',importSubjects);const input=document.getElementById('subjectBulkFile'),dz=document.getElementById('subjectDropZone');input.addEventListener('change',()=>readSubjectFile(input.files?.[0]));['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,x=>{x.preventDefault();dz.classList.add('dragover')}));['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,x=>{x.preventDefault();dz.classList.remove('dragover')}));dz.addEventListener('drop',x=>readSubjectFile(x.dataTransfer.files?.[0]));
  }
  function downloadSubjectTemplate(){downloadCSV('subject_bulk_upload_template.csv',[['Code','Subject','Branch','Semester','Credits','Internal','External'],['23CS601','Artificial Intelligence','CSE','III-II',3,30,70],['23CE601','Structural Engineering','CIVIL','III-II',3,30,70]])}
  function h(v){return String(v??'').trim().toLowerCase().replace(/[_\-./]/g,' ').replace(/\s+/g,' ')}
  function cv(row,names){const obj={};Object.keys(row||{}).forEach(k=>obj[h(k)]=row[k]);for(const n of names){if(Object.prototype.hasOwnProperty.call(obj,h(n)))return obj[h(n)]}return''}
  function parseCsvLocal(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(ch===','&&!quoted){row.push(cell);cell=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);cell='';if(row.some(v=>String(v).trim()))rows.push(row);row=[]}else cell+=ch}row.push(cell);if(row.some(v=>String(v).trim()))rows.push(row);if(!rows.length)return[];const headers=rows[0].map(x=>String(x).trim());return rows.slice(1).map(r=>Object.fromEntries(headers.map((x,i)=>[x,r[i]??''])))}
  function subjectRow(row,i){ensureMasters();const subject={code:String(cv(row,['Code','Subject Code'])||'').trim().toUpperCase(),name:String(cv(row,['Subject','Subject Name','Name'])||'').trim(),branch:String(cv(row,['Branch','Department'])||'').trim().toUpperCase(),semester:String(cv(row,['Semester','Sem'])||'').trim().toUpperCase(),credits:Number(cv(row,['Credits','Credit'])||0),internal:Number(cv(row,['Internal','Internal Marks'])||0),external:Number(cv(row,['External','External Marks'])||0)};const errors=[];if(!subject.code)errors.push('Code missing');if(!subject.name)errors.push('Subject missing');if(!activeBranches().some(x=>x.code===subject.branch))errors.push('Invalid branch');if(!activeSemesters().some(x=>x.label===subject.semester))errors.push('Invalid semester');if(!(subject.credits>0))errors.push('Invalid credits');if(subject.internal<0||subject.external<0||subject.internal+subject.external<=0)errors.push('Invalid marks');const dup=(state.subjects||[]).find(x=>String(x.code).toUpperCase()===subject.code);return{index:i+1,subject,errors,duplicateId:dup?.id||null}}
  async function readSubjectFile(file){if(!file)return;try{let rows=[],ext=file.name.split('.').pop().toLowerCase();if(ext==='csv')rows=parseCsvLocal(await file.text());else if(['xlsx','xls'].includes(ext)){if(typeof XLSX==='undefined')throw new Error('Excel reader not available');const wb=XLSX.read(await file.arrayBuffer(),{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]];rows=XLSX.utils.sheet_to_json(ws,{defval:''})}else throw new Error('Choose CSV, XLSX or XLS');if(!rows.length)throw new Error('No subject rows found');subjectRows=rows.map(subjectRow);renderSubjectBulkPreview()}catch(err){showMsg(err.message||'Could not read subject file')}}
  function openSubjectBulkModal(){subjectRows=[];document.getElementById('subjectBulkFile').value='';document.getElementById('subjectBulkSummary').hidden=true;document.getElementById('subjectBulkPreviewWrap').hidden=true;document.getElementById('subjectImportBtn').disabled=true;document.getElementById('subjectBulkBackdrop').hidden=false}
  function closeSubjectBulkModal(){document.getElementById('subjectBulkBackdrop').hidden=true;subjectRows=[]}
  function renderSubjectBulkPreview(){if(!subjectRows.length)return;const policy=document.getElementById('subjectDuplicatePolicy').value,valid=subjectRows.filter(x=>!x.errors.length),invalid=subjectRows.filter(x=>x.errors.length),dups=valid.filter(x=>x.duplicateId),fresh=valid.filter(x=>!x.duplicateId);const sm=document.getElementById('subjectBulkSummary');sm.hidden=false;sm.innerHTML=`<div class="summary-box"><small>Total</small><b>${subjectRows.length}</b></div><div class="summary-box"><small>New</small><b>${fresh.length}</b></div><div class="summary-box"><small>Existing</small><b>${dups.length}</b></div><div class="summary-box"><small>Invalid</small><b>${invalid.length}</b></div>`;document.getElementById('subjectBulkPreviewWrap').hidden=false;document.getElementById('subjectBulkPreviewBody').innerHTML=subjectRows.slice(0,100).map(r=>{const x=r.subject;let status='<span class="validation-ok">Ready</span>';if(r.errors.length)status=`<span class="validation-error">${e(r.errors.join(', '))}</span>`;else if(r.duplicateId)status=`<span class="validation-update">Will ${policy==='update'?'update':'skip'}</span>`;return `<tr><td>${r.index}</td><td><b>${e(x.code)}</b></td><td>${e(x.name)}</td><td>${e(x.branch)}</td><td>${e(x.semester)}</td><td>${x.credits}</td><td>${x.internal}</td><td>${x.external}</td><td>${status}</td></tr>`}).join('');const count=valid.filter(x=>!x.duplicateId||policy==='update').length,btn=document.getElementById('subjectImportBtn');btn.disabled=!count;btn.textContent=count?`Import ${count} Subject${count===1?'':'s'}`:'Import Subjects'}
  function importSubjects(){const policy=document.getElementById('subjectDuplicatePolicy').value;let add=0,upd=0,skip=0,bad=0;subjectRows.forEach(r=>{if(r.errors.length){bad++;return}if(r.duplicateId){if(policy==='update'){state.subjects=state.subjects.map(s=>s.id===r.duplicateId?{id:r.duplicateId,...r.subject}:s);upd++}else skip++;return}state.subjects.push({id:nextId(state.subjects),...r.subject});add++});saveData();renderSubjects();renderBranches();renderSemesters();closeSubjectBulkModal();showMsg(`Subjects: ${add} added, ${upd} updated, ${skip} skipped, ${bad} invalid`)}

  function installDualHallTicket(){const form=document.querySelector('#halltickets .form-grid.single');if(!form||document.getElementById('hallStudentSelect2'))return;const first=document.getElementById('hallStudentSelect')?.closest('label');if(first){first.childNodes[0].textContent='Student 1';const label=document.createElement('label');label.innerHTML='Student 2<select class="input" id="hallStudentSelect2"></select>';first.after(label);const note=document.createElement('p');note.className='hall-note';note.textContent='Print layout: two student hall tickets on one A4 page.';form.after(note)}
    const originalPopulate=populateHallSelects;populateHallSelects=function(){originalPopulate();const sel=document.getElementById('hallStudentSelect2');if(sel)sel.innerHTML='<option value="">Select second student</option>'+(state.students||[]).map(s=>`<option value="${s.id}">${e(s.hall)} — ${e(s.name)}</option>`).join('')};populateHallSelects();
    const btn=document.getElementById('generateHallBtn');btn.addEventListener('click',ev=>{ev.preventDefault();ev.stopImmediatePropagation();generateDualHall()},true);
  }
  function hallHalf(student,exam,centre){if(!student)return `<section class="dual-ticket-half"><p class="muted">No student selected.</p></section>`;const subjects=(state.subjects||[]).filter(s=>s.branch===student.branch&&s.semester===exam.semester);return `<section class="dual-ticket-half"><h3 class="dual-ticket-title">${e(state.settings.collegeName||'ABC College of Engineering')}</h3><p class="dual-ticket-sub">Autonomous Institution</p><div class="dual-ticket-label">HALL TICKET</div><table class="dual-info"><tr><td>Hall Ticket</td><td>${e(student.hall)}</td><td>Student</td><td>${e(student.name)}</td></tr><tr><td>Branch</td><td>${e(student.branch)}</td><td>Semester</td><td>${e(exam.semester)}</td></tr><tr><td>Examination</td><td colspan="3">${e(exam.name)}</td></tr><tr><td>Centre</td><td colspan="3">${e(centre)}</td></tr><tr><td>Date</td><td>${e(formatDate(exam.date))}</td><td>Session</td><td>${e(exam.session)}</td></tr></table><table class="dual-subjects"><thead><tr><th>Subject Code</th><th>Subject Name</th></tr></thead><tbody>${subjects.map(s=>`<tr><td>${e(s.code)}</td><td>${e(s.name)}</td></tr>`).join('')||'<tr><td colspan="2">No subjects configured</td></tr>'}</tbody></table><div class="dual-sign"><span>Student Signature: __________</span><span>Controller of Examinations</span></div></section>`}
  function generateDualHall(){const s1=(state.students||[]).find(s=>s.id===Number(document.getElementById('hallStudentSelect').value)),s2=(state.students||[]).find(s=>s.id===Number(document.getElementById('hallStudentSelect2').value)),exam=(state.exams||[]).find(x=>x.id===Number(document.getElementById('hallExamSelect').value)),centre=document.getElementById('examCentre').value;if(!s1||!s2||!exam){showMsg('Select Student 1, Student 2 and Examination');return}const preview=document.getElementById('hallTicketPreview');preview.innerHTML=`<div class="dual-ticket-page">${hallHalf(s1,exam,centre)}${hallHalf(s2,exam,centre)}</div>`;showMsg('Two-student hall ticket generated')}

  function refreshAllMasters(){refreshBranchFilter();renderBranches();renderSemesters();renderStudents();}
  function installQuickActions(){const q=document.querySelector('#dashboard .quick-grid');if(!q)return;if(!document.getElementById('branchQuick')){const b=document.createElement('button');b.className='quick-action';b.id='branchQuick';b.innerHTML='<span>⌘</span><b>Branch Master</b><small>Manage academic branches</small>';b.addEventListener('click',()=>{navigate('branches');renderBranches()});q.appendChild(b)}if(!document.getElementById('semesterQuick')){const s=document.createElement('button');s.className='quick-action';s.id='semesterQuick';s.innerHTML='<span>◫</span><b>Semester Master</b><small>Manage semesters</small>';s.addEventListener('click',()=>{navigate('semesters');renderSemesters()});q.appendChild(s)}}

  ensureMasters();injectStyles();addNavAndViews();installStudentFilters();installBulkSubject();installDualHallTicket();installQuickActions();renderBranches();renderSemesters();renderStudents();
  document.getElementById('resetDemoBtn')?.addEventListener('click',()=>setTimeout(()=>{ensureMasters();refreshAllMasters()},0));
})();