(function(){
  const STYLE_ID='attendance-module-styles-v1';
  const YEAR_ORDER=['I','II','III','IV'];
  let attendancePages=[];
  const bookletMap={};

  function getState(){try{return JSON.parse(localStorage.getItem('campusExamData_v1'))||{students:[],branches:[],settings:{}}}catch{return{students:[],branches:[],settings:{}}}}
  function msg(t){if(typeof toast==='function')toast(t);else alert(t)}
  function e(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
  function fmtDate(v){if(!v)return'';const [y,m,d]=v.split('-');return `${d}.${m}.${y}`}
  function safeSheet(v,i){return (String(v||`Room ${i+1}`).replace(/[\\/?*\[\]:]/g,'-').slice(0,31)||`Room ${i+1}`)}

  function injectStyles(){
    if(document.getElementById(STYLE_ID))return;
    const st=document.createElement('style');st.id=STYLE_ID;st.textContent=`
      .attendance-layout{display:grid;grid-template-columns:minmax(320px,410px) 1fr;gap:18px;align-items:start}.attendance-panel{position:sticky;top:100px}.attendance-form{display:grid;grid-template-columns:1fr 1fr;gap:12px}.attendance-form label{display:grid;gap:6px;font-size:13px;font-weight:700}.attendance-form .wide{grid-column:1/-1}.attendance-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.attendance-note{font-size:12px;color:var(--muted);line-height:1.5;margin-top:10px}.attendance-status{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:14px}.attendance-status>div{background:var(--surface-2);border:1px solid var(--line);border-radius:12px;padding:11px}.attendance-status small{display:block;color:var(--muted)}.attendance-status b{font-size:19px}.attendance-preview{display:grid;gap:18px}.attendance-paper{background:#fff;color:#111;border:1px solid #cfd5df;box-shadow:0 8px 22px rgba(15,23,42,.09);padding:24px;min-height:1000px;font-family:'Times New Roman',serif}.att-college{text-align:center;font-family:Arial,sans-serif;font-size:21px;font-weight:900;margin:0 0 18px}.att-meta{width:100%;border-collapse:collapse;min-width:0}.att-meta td{border:1px solid #555;padding:7px 9px;font-size:13px;background:#fff;color:#111}.att-meta td:first-child{width:29%;font-weight:700}.att-title{text-align:center;font-size:18px;font-weight:800;margin:18px 0}.att-room{display:flex;align-items:center;gap:14px;margin:0 0 14px 5px;font-weight:700}.att-room-box{min-width:64px;height:32px;border:1px solid #444;display:grid;place-items:center;padding:0 8px}.att-table{width:100%;min-width:0;border-collapse:collapse}.att-table th,.att-table td{border:1px solid #555;background:#fff;color:#111;text-align:center;padding:5px 6px;font-size:11px}.att-table th{font-weight:800}.att-table th:nth-child(1){width:9%}.att-table th:nth-child(2){width:27%}.att-table th:nth-child(3){width:25%}.att-table th:nth-child(4){width:39%}.att-table tbody td{height:27px}.att-booklet{width:100%;border:0;text-align:center;background:#fff;color:#111;font:inherit;outline:none}.att-absent{font-weight:900;color:#b91c1c}.att-counts{margin:28px auto 0;width:min(430px,95%)}.att-count-line{display:grid;grid-template-columns:1fr 72px;align-items:center;text-align:right;font-size:14px}.att-count-line>div:last-child{height:34px;border:1px solid #555;display:grid;place-items:center;margin-left:10px}.att-sign{margin-top:30px;font-size:15px}.att-sign-nos{margin-left:46%;display:grid;gap:24px;margin-top:18px}.attendance-empty{padding:80px 20px;text-align:center;color:var(--muted);border:2px dashed var(--line);border-radius:18px;background:var(--surface)}
      @media(max-width:1100px){.attendance-layout{grid-template-columns:1fr}.attendance-panel{position:static}}@media(max-width:650px){.attendance-form{grid-template-columns:1fr}.attendance-form .wide{grid-column:auto}.attendance-status{grid-template-columns:1fr 1fr}.attendance-paper{padding:14px;overflow:auto}}
    `;document.head.appendChild(st);
  }

  function branchOptions(){const s=getState(),branches=(s.branches||[]).filter(x=>(x.status||'Active')==='Active');const codes=branches.length?branches.map(x=>x.code):[...new Set((s.students||[]).map(x=>x.branch).filter(Boolean))];return '<option value="">All Branches</option>'+codes.map(x=>`<option>${e(x)}</option>`).join('')}

  function addNavAndView(){
    const nav=document.querySelector('.nav'),content=document.querySelector('.content');
    if(nav&&!document.querySelector('[data-view="attendance"]')){
      const btn=document.createElement('button');btn.className='nav-link';btn.dataset.view='attendance';btn.innerHTML='<span>☑</span>Attendance';
      const reports=document.querySelector('[data-view="reports"]');nav.insertBefore(btn,reports||null);btn.addEventListener('click',()=>{navigate('attendance');refreshStats()});
    }
    if(content&&!document.getElementById('attendance')){
      const sec=document.createElement('section');sec.className='view';sec.id='attendance';sec.innerHTML=`
        <div class="section-toolbar"><div><h3>Attendance</h3><p>Generate room-wise examination attendance sheets in the Ashoka format.</p></div><div class="button-row"><button class="btn btn-outline" id="attendanceExcel">Export Excel</button><button class="btn btn-primary" id="attendancePdf">Export PDF</button></div></div>
        <div class="attendance-layout">
          <div class="card attendance-panel"><h3>Attendance Details</h3><div class="attendance-form">
            <label class="wide">College Name<input class="input" id="attCollege" value="ASHOKA WOMEN'S ENGINEERING COLLEGE - 2T"></label>
            <label>Date of Examination<input class="input" id="attDate" type="date" value="2026-08-24"></label>
            <label>Rows per Attendance Sheet<select class="input" id="attRowsPerPage"><option selected>24</option><option>30</option><option>36</option><option>48</option></select></label>
            <label class="wide">Year & Semester / Examination<input class="input" id="attYearText" value="III B. Tech Year I Semester (R23) MID - I Examinations August- 2026"></label>
            <label class="wide">Name of the Subject(s)<input class="input" id="attSubjects" value="ADICA,MM,WRE & PE"></label>
            <label>Branch<select class="input" id="attBranch">${branchOptions()}</select></label>
            <label>Year<select class="input" id="attYear"><option value="">All Years</option>${YEAR_ORDER.map(x=>`<option>${x}</option>`).join('')}</select></label>
            <label>Semester<select class="input" id="attSemester"><option value="">All Semesters</option><option>I</option><option>II</option></select></label>
            <label>Room Number(s)<input class="input" id="attRooms" placeholder="e.g. 101, 102"></label>
            <label class="wide">Absent Hall Ticket No(s)<textarea class="input" id="attAbsent" rows="3" placeholder="Optional: enter hall tickets separated by comma, space or new line"></textarea></label>
          </div><div class="attendance-actions"><button class="btn btn-primary" id="attGenerate" type="button">Generate Attendance</button><button class="btn btn-outline" id="attClear" type="button">Clear</button></div><p class="attendance-note">Students are loaded from Student Master using Branch, Year and Semester. Booklet S.No can be entered directly in the preview before exporting.</p></div>
          <div><div class="attendance-status" id="attStatus"><div><small>Filtered Students</small><b>0</b></div><div><small>Absent</small><b>0</b></div><div><small>Present</small><b>0</b></div><div><small>Sheets</small><b>0</b></div></div><div class="attendance-preview" id="attPreview"><div class="attendance-empty">Choose Branch / Year / Semester and click <b>Generate Attendance</b>.</div></div></div>
        </div>`;content.appendChild(sec);
    }
  }

  function selectedStudents(){const s=getState(),branch=document.getElementById('attBranch')?.value||'',year=document.getElementById('attYear')?.value||'',sem=document.getElementById('attSemester')?.value||'';return (s.students||[]).filter(x=>(x.status||'Active')==='Active'&&(!branch||x.branch===branch)&&(!year||x.year===year)&&(!sem||x.sem===sem)).sort((a,b)=>String(a.hall).localeCompare(String(b.hall)))}
  function absentSet(){return new Set(String(document.getElementById('attAbsent')?.value||'').split(/[\s,;]+/).map(x=>x.trim().toUpperCase()).filter(Boolean))}
  function refreshStats(){const students=selectedStudents(),abs=absentSet(),absCount=students.filter(x=>abs.has(String(x.hall).toUpperCase())).length,rows=Number(document.getElementById('attRowsPerPage')?.value||24),sheets=students.length?Math.ceil(students.length/rows):0;const bs=document.querySelectorAll('#attStatus b');if(bs.length===4){bs[0].textContent=students.length;bs[1].textContent=absCount;bs[2].textContent=Math.max(0,students.length-absCount);bs[3].textContent=sheets}}
  function meta(){return{college:document.getElementById('attCollege').value.trim(),date:document.getElementById('attDate').value,yearText:document.getElementById('attYearText').value.trim(),subjects:document.getElementById('attSubjects').value.trim()}}

  function buildPages(){const students=selectedStudents();if(!students.length){msg('No students found for the selected filters');return []}const per=Number(document.getElementById('attRowsPerPage').value||24),rooms=document.getElementById('attRooms').value.split(',').map(x=>x.trim()).filter(Boolean),count=Math.ceil(students.length/per);return Array.from({length:count},(_,i)=>({room:rooms[i]||(count===1?(rooms[0]||''):`Room ${i+1}`),students:students.slice(i*per,(i+1)*per),pageIndex:i}))}

  function renderAttendance(){attendancePages=buildPages();if(!attendancePages.length)return;const m=meta(),abs=absentSet(),preview=document.getElementById('attPreview');preview.innerHTML=attendancePages.map((p,pi)=>{const absentCount=p.students.filter(s=>abs.has(String(s.hall).toUpperCase())).length,present=p.students.length-absentCount;return `<article class="attendance-paper" data-att-page="${pi}"><h2 class="att-college">${e(m.college)}</h2><table class="att-meta"><tr><td>Date of Examination:</td><td>${e(fmtDate(m.date))}</td></tr><tr><td>Year & Semester:</td><td>${e(m.yearText)}</td></tr><tr><td>Name of the Subject(s):</td><td>${e(m.subjects)}</td></tr></table><div class="att-title">Attendance</div><div class="att-room">Room Number <div class="att-room-box">${e(p.room)}</div></div><table class="att-table"><thead><tr><th>S.No</th><th>Hall Ticket No.</th><th>Booklet S.NO</th><th>Signature of the student</th></tr></thead><tbody>${p.students.map((s,i)=>{const hall=String(s.hall),isAbs=abs.has(hall.toUpperCase());return `<tr><td>${i+1}</td><td><b>${e(hall)}</b></td><td><input class="att-booklet" data-att-hall="${e(hall)}" value="${e(bookletMap[hall]||'')}" placeholder=""></td><td>${isAbs?'<span class="att-absent">ABSENT</span>':''}</td></tr>`}).join('')}</tbody></table><div class="att-counts"><div class="att-count-line"><div>Number of Candidates Registered:</div><div>${p.students.length}</div></div><div class="att-count-line"><div>Number of Candidates Absent:</div><div>${absentCount||''}</div></div><div class="att-count-line"><div>Number of Candidates Present:</div><div>${present}</div></div></div><div class="att-sign">Signature of the Invigilator(s)<div class="att-sign-nos"><span>1</span><span>2</span></div></div></article>`}).join('');preview.querySelectorAll('.att-booklet').forEach(inp=>inp.addEventListener('input',()=>bookletMap[inp.dataset.attHall]=inp.value));refreshStats();msg(`${attendancePages.length} attendance sheet${attendancePages.length===1?'':'s'} generated`)}

  async function loadScript(src,test){if(test())return;await new Promise((res,rej)=>{const s=document.createElement('script');s.src=src;s.onload=res;s.onerror=rej;document.head.appendChild(s)})}
  async function ensurePdf(){await loadScript('https://cdn.jsdelivr.net/npm/jspdf@2.5.1/dist/jspdf.umd.min.js',()=>!!window.jspdf?.jsPDF)}
  async function ensureXlsx(){await loadScript('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js',()=>!!window.XLSX)}

  async function exportPdf(){if(!attendancePages.length){renderAttendance();if(!attendancePages.length)return}try{await ensurePdf();const {jsPDF}=window.jspdf,m=meta(),abs=absentSet(),doc=new jsPDF({orientation:'portrait',unit:'mm',format:'a4'});attendancePages.forEach((p,pi)=>{if(pi)doc.addPage();doc.setTextColor(0);doc.setFont('helvetica','bold');doc.setFontSize(14);doc.text(m.college||"ASHOKA WOMEN'S ENGINEERING COLLEGE - 2T",105,13,{align:'center'});const x=10,y=21,w=190,labelW=48,rh=8;for(let r=0;r<3;r++){doc.rect(x,y+r*rh,w,rh);doc.line(x+labelW,y+r*rh,x+labelW,y+(r+1)*rh)}doc.setFontSize(8);doc.text('Date of Examination:',x+2,y+5.2);doc.text('Year & Semester:',x+2,y+rh+5.2);doc.text('Name of the Subject(s):',x+2,y+rh*2+5.2);doc.setFont('helvetica','normal');doc.text(fmtDate(m.date),x+labelW+2,y+5.2);doc.setFontSize(7.2);doc.text(doc.splitTextToSize(m.yearText,137),x+labelW+2,y+rh+4.8);doc.text(doc.splitTextToSize(m.subjects,137),x+labelW+2,y+rh*2+4.8);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('Attendance',105,51,{align:'center'});doc.setFontSize(8.5);doc.text('Room Number',15,61);doc.rect(46,55,23,9);doc.setFont('helvetica','normal');doc.text(String(p.room||''),57.5,61,{align:'center'});
        const tx=10,ty=68,col=[15,52,46,77],headerH=8,rowH=Math.min(7.2,150/Math.max(p.students.length,1));let cx=tx;doc.setFontSize(7.3);doc.setFont('helvetica','bold');['S.No','Hall Ticket No.','Booklet S.NO','Signature of the student'].forEach((h,i)=>{doc.rect(cx,ty,col[i],headerH);doc.text(h,cx+col[i]/2,ty+5.1,{align:'center'});cx+=col[i]});doc.setFont('helvetica','normal');p.students.forEach((s,i)=>{let xx=tx,yy=ty+headerH+i*rowH;const hall=String(s.hall),isAbs=abs.has(hall.toUpperCase()),vals=[String(i+1),hall,String(bookletMap[hall]||''),isAbs?'ABSENT':''];vals.forEach((v,c)=>{doc.rect(xx,yy,col[c],rowH);if(v){if(c===3&&isAbs)doc.setFont('helvetica','bold');doc.text(v,xx+col[c]/2,yy+rowH*.68,{align:'center'});if(c===3&&isAbs)doc.setFont('helvetica','normal')}xx+=col[c]})});const tableEnd=ty+headerH+p.students.length*rowH,registered=p.students.length,absCount=p.students.filter(s=>abs.has(String(s.hall).toUpperCase())).length,present=registered-absCount,cy=Math.min(240,tableEnd+13),lx=103,bx=105,bw=18,bh=8;doc.setFontSize(8.3);doc.text('Number of Candidates Registered:',lx,cy+5.5,{align:'right'});doc.rect(bx,cy,bw,bh);doc.text(String(registered),bx+bw/2,cy+5.5,{align:'center'});doc.text('Number of Candidates Absent:',lx,cy+13.5,{align:'right'});doc.rect(bx,cy+8,bw,bh);doc.text(absCount?String(absCount):'',bx+bw/2,cy+13.5,{align:'center'});doc.text('Number of Candidates Present:',lx,cy+21.5,{align:'right'});doc.rect(bx,cy+16,bw,bh);doc.text(String(present),bx+bw/2,cy+21.5,{align:'center'});doc.setFontSize(9);doc.text('Signature of the Invigilator(s)',10,272);doc.text('1',81,282);doc.text('2',81,291)});doc.save(`Attendance_${m.date||'Exam'}.pdf`);msg('Attendance PDF exported')}catch(err){console.error(err);msg('Could not export PDF. Check internet connection and try again.')}}

  async function exportExcel(){if(!attendancePages.length){renderAttendance();if(!attendancePages.length)return}try{await ensureXlsx();const wb=XLSX.utils.book_new(),m=meta(),abs=absentSet();attendancePages.forEach((p,pi)=>{const rows=[[m.college],['Date of Examination:',fmtDate(m.date)],['Year & Semester:',m.yearText],['Name of the Subject(s):',m.subjects],[],['Attendance'],['Room Number',p.room],[],['S.No','Hall Ticket No.','Booklet S.NO','Signature of the student']];p.students.forEach((s,i)=>{const hall=String(s.hall),isAbs=abs.has(hall.toUpperCase());rows.push([i+1,hall,bookletMap[hall]||'',isAbs?'ABSENT':''])});const ac=p.students.filter(s=>abs.has(String(s.hall).toUpperCase())).length;rows.push([],['Number of Candidates Registered:',p.students.length],['Number of Candidates Absent:',ac||''],['Number of Candidates Present:',p.students.length-ac],[],['Signature of the Invigilator(s)'],['1'],['2']);const ws=XLSX.utils.aoa_to_sheet(rows);ws['!cols']=[{wch:10},{wch:28},{wch:22},{wch:38}];ws['!merges']=[{s:{r:0,c:0},e:{r:0,c:3}},{s:{r:5,c:0},e:{r:5,c:3}}];XLSX.utils.book_append_sheet(wb,ws,safeSheet(p.room,pi))});XLSX.writeFile(wb,`Attendance_${m.date||'Exam'}.xlsx`);msg('Attendance Excel exported')}catch(err){console.error(err);msg('Could not export Excel. Check internet connection and try again.')}}

  function install(){injectStyles();addNavAndView();['attBranch','attYear','attSemester','attRowsPerPage','attAbsent'].forEach(id=>document.getElementById(id)?.addEventListener('input',refreshStats));document.getElementById('attGenerate')?.addEventListener('click',renderAttendance);document.getElementById('attendancePdf')?.addEventListener('click',exportPdf);document.getElementById('attendanceExcel')?.addEventListener('click',exportExcel);document.getElementById('attClear')?.addEventListener('click',()=>{document.getElementById('attAbsent').value='';document.getElementById('attRooms').value='';attendancePages=[];document.getElementById('attPreview').innerHTML='<div class="attendance-empty">Choose Branch / Year / Semester and click <b>Generate Attendance</b>.</div>';refreshStats()});const q=document.querySelector('#dashboard .quick-grid');if(q&&!document.getElementById('attendanceQuick')){const b=document.createElement('button');b.className='quick-action';b.id='attendanceQuick';b.innerHTML='<span>☑</span><b>Attendance</b><small>Generate exam attendance sheets</small>';b.addEventListener('click',()=>{navigate('attendance');refreshStats()});q.appendChild(b)}refreshStats()}
  install();
})();