(function(){
  const ROLE_KEY='campusExamRole_v1';
  const ROLES={
    admin:{label:'Admin',desc:'Full system access',views:['dashboard','faculty','students','branches','semesters','subjects','examsection','exams','halltickets','seating','attendance','marks','reports','settings','roles']},
    exam:{label:'Exam Section',desc:'Examination operations and reports',views:['dashboard','faculty','students','subjects','examsection','exams','halltickets','seating','attendance','marks','reports']},
    faculty:{label:'Faculty',desc:'Student, subject and marks access',views:['dashboard','students','subjects','marks']},
    student:{label:'Students',desc:'Limited student-facing access',views:['dashboard','halltickets','marks']}
  };
  let currentRole=localStorage.getItem(ROLE_KEY)||'admin';if(!ROLES[currentRole])currentRole='admin';
  function e(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
  function msg(t){if(typeof toast==='function')toast(t);else alert(t)}

  function styles(){if(document.getElementById('role-module-styles'))return;const s=document.createElement('style');s.id='role-module-styles';s.textContent=`
    .role-chip{display:inline-flex;align-items:center;gap:6px;border-radius:999px;padding:5px 9px;background:var(--surface-2);border:1px solid var(--line);font-size:12px;font-weight:800}.roles-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:18px}.role-card{border:1px solid var(--line);background:var(--surface);border-radius:16px;padding:16px;text-align:left;color:var(--text)}.role-card.active{outline:2px solid var(--primary);border-color:transparent}.role-card b,.role-card small{display:block}.role-card small{color:var(--muted);margin-top:5px}.perm-yes{font-weight:900;color:var(--success)}.perm-no{font-weight:900;color:var(--muted)}.role-hidden{display:none!important}.role-readonly-note{margin:0 0 14px;padding:10px 12px;border-radius:12px;background:var(--surface-2);border:1px solid var(--line);font-size:12px;font-weight:700}@media(max-width:900px){.roles-grid{grid-template-columns:1fr 1fr}}@media(max-width:600px){.roles-grid{grid-template-columns:1fr}}
  `;document.head.appendChild(s)}

  function ensureRolesView(){const content=document.querySelector('.content');if(!content||document.getElementById('roles'))return;const sec=document.createElement('section');sec.className='view';sec.id='roles';sec.innerHTML=`<div class="section-toolbar"><div><h3>Roles & Permissions</h3><p>Access is assigned automatically after login.</p></div><span class="role-chip" id="roleCurrentChip"></span></div><div class="roles-grid" id="rolesGrid"></div><div class="card"><div class="card-head"><div><h3>Permission Matrix</h3><p>Prototype interface permissions. Production security requires backend authentication.</p></div></div><div class="table-wrap"><table><thead><tr><th>Module</th><th>Admin</th><th>Exam Section</th><th>Faculty</th><th>Students</th></tr></thead><tbody id="rolePermissionBody"></tbody></table></div></div>`;content.appendChild(sec)}
  function ensureRolesNav(){const nav=document.querySelector('.nav');if(!nav||document.querySelector('[data-view="roles"]'))return;const b=document.createElement('button');b.className='nav-link';b.dataset.view='roles';b.innerHTML='<span>♜</span>Roles';const settings=document.querySelector('[data-view="settings"]');nav.insertBefore(b,settings||null);b.addEventListener('click',()=>{if(currentRole!=='admin')return msg('Roles are available to Admin only');navigate('roles');renderRoles()})}

  function renderRoles(){const grid=document.getElementById('rolesGrid');if(!grid)return;const chip=document.getElementById('roleCurrentChip');if(chip)chip.textContent=`Current Role: ${ROLES[currentRole].label}`;grid.innerHTML=Object.entries(ROLES).map(([k,r])=>`<div class="role-card ${k===currentRole?'active':''}"><b>${e(r.label)}</b><small>${e(r.desc)}</small></div>`).join('');const modules=[['Dashboard','dashboard'],['Faculty','faculty'],['Students','students'],['Branches','branches'],['Semesters','semesters'],['Subjects','subjects'],['Examinations','exams'],['Hall Tickets','halltickets'],['Seating Plan','seating'],['Exam Attendance','attendance'],['Marks & Results','marks'],['Reports','reports'],['Settings','settings'],['Roles','roles']];document.getElementById('rolePermissionBody').innerHTML=modules.map(([label,v])=>`<tr><td><b>${label}</b></td>${['admin','exam','faculty','student'].map(k=>`<td class="${ROLES[k].views.includes(v)?'perm-yes':'perm-no'}">${ROLES[k].views.includes(v)?'✓':'—'}</td>`).join('')}</tr>`).join('')}

  function updateRoleProfile(){if(window.CampusSession)return;const p=document.querySelector('.sidebar-footer .profile');if(!p)return;const r=ROLES[currentRole],strong=p.querySelector('strong'),span=p.querySelector('span'),avatar=p.querySelector('.avatar');if(strong)strong.textContent=r.label;if(span)span.textContent=r.desc;if(avatar)avatar.textContent=r.label.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
  function studentReadOnly(){const isStudent=currentRole==='student';const marks=document.getElementById('marks');if(marks){let n=document.getElementById('studentRoleReadOnlyNote');if(isStudent&&!n){n=document.createElement('div');n.id='studentRoleReadOnlyNote';n.className='role-readonly-note';n.textContent='Student access is read-only. Marks entry, saving and bulk upload are disabled.';marks.querySelector('.section-toolbar')?.after(n)}if(!isStudent&&n)n.remove();marks.querySelectorAll('input.mark-input,#saveMarksBtn,#bulkMarksBtn,#downloadMarksTemplateBtn').forEach(el=>{el.disabled=isStudent;if(el.id==='bulkMarksBtn')el.classList.toggle('role-hidden',isStudent)})}const hall=document.getElementById('halltickets');if(hall)hall.querySelectorAll('#generateHallBtn,#hallBranchFilter,#hallYearFilter,#hallSemesterFilter,#hallExamSelect,#examCentre').forEach(el=>el.disabled=isStudent)}

  function applyAccess(){const allowed=new Set(ROLES[currentRole].views);document.querySelectorAll('.nav-link[data-view]').forEach(btn=>btn.classList.toggle('role-hidden',!allowed.has(btn.dataset.view)));const examWrap=document.getElementById('examModuleNav');if(examWrap)examWrap.classList.toggle('role-hidden',!['exams','halltickets','seating','attendance','marks'].some(v=>allowed.has(v)));document.querySelectorAll('[data-jump]').forEach(btn=>{if(btn.dataset.jump)btn.classList.toggle('role-hidden',!allowed.has(btn.dataset.jump))});studentReadOnly();updateRoleProfile();const active=document.querySelector('.view.active')?.id;if(active&&!allowed.has(active)&&typeof navigate==='function')navigate('dashboard');renderRoles()}
  function setRole(role,silent=false){if(!ROLES[role])return;currentRole=role;localStorage.setItem(ROLE_KEY,role);applyAccess();if(!silent)msg(`Role changed to ${ROLES[role].label}`)}

  function loadExtras(){const loadLogin=()=>{if(document.querySelector('script[data-login-module]'))return;const l=document.createElement('script');l.src='login-module.js';l.dataset.loginModule='true';document.body.appendChild(l)};if(document.querySelector('script[data-faculty-module]')){loadLogin();return}const f=document.createElement('script');f.src='faculty-module.js';f.dataset.facultyModule='true';f.onload=loadLogin;f.onerror=loadLogin;document.body.appendChild(f)}

  styles();ensureRolesView();ensureRolesNav();renderRoles();applyAccess();window.CampusRoles={setRole,applyAccess,getRole:()=>currentRole,roles:ROLES};setTimeout(()=>{ensureRolesNav();applyAccess()},500);loadExtras();
})();