(function(){
  const STYLE_ID='seating-plan-styles-v1';
  if(!document.getElementById(STYLE_ID)){
    const st=document.createElement('style');st.id=STYLE_ID;st.textContent=`
    .seat-layout{display:grid;grid-template-columns:minmax(320px,420px) 1fr;gap:18px;align-items:start}.seat-panel{position:sticky;top:100px}.seat-form{display:grid;grid-template-columns:1fr 1fr;gap:12px}.seat-form label{display:grid;gap:6px;font-size:13px;font-weight:700}.seat-form .wide{grid-column:1/-1}.seat-source{display:grid;grid-template-columns:1fr auto;gap:8px}.seat-textarea{min-height:135px;resize:vertical;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px}.seat-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.seat-help{margin:10px 0 0;color:var(--muted);font-size:12px;line-height:1.5}.seat-preview-wrap{display:grid;gap:18px}.seat-paper{background:#fff;color:#111;border:1px solid #cfd5df;box-shadow:0 8px 22px rgba(15,23,42,.09);padding:28px;min-height:940px;font-family:'Times New Roman',serif}.seat-paper-title{text-align:center;font-family:Arial,sans-serif;font-size:22px;font-weight:900;margin:0 0 22px}.seat-meta{width:100%;border-collapse:collapse;min-width:0}.seat-meta td{border:1px solid #555;padding:7px 9px;font-size:13px;background:#fff;color:#111}.seat-meta td:first-child{width:29%;font-weight:700}.seat-plan-title{text-align:center;font-size:18px;font-weight:800;margin:24px 0}.seat-room{display:flex;align-items:center;gap:14px;margin:0 0 30px 16px;font-weight:700}.seat-room-box{min-width:58px;height:34px;border:1px solid #333;display:grid;place-items:center;padding:0 8px}.seat-grid{display:grid;gap:9px}.seat-row{display:grid;grid-template-columns:86px repeat(4,1fr);gap:11px;align-items:center}.seat-row-label{font-weight:700;font-size:13px;text-align:right;padding-right:5px}.seat-row-label span{margin-left:8px}.seat-box{height:31px;border:1px solid #555;display:grid;place-items:center;font-size:11px;white-space:nowrap;background:#fff}.seat-counts{margin:78px auto 0;width:min(410px,90%)}.seat-count-line{display:grid;grid-template-columns:1fr 72px;align-items:center;text-align:right;font-size:15px}.seat-count-line>div:last-child{height:37px;border:1px solid #555;display:grid;place-items:center;margin-left:10px}.seat-count-line input{width:100%;height:35px;border:0;text-align:center;font:inherit;background:#fff;color:#111}.seat-sign{margin-top:42px;font-size:16px}.seat-sign-numbers{margin-left:46%;display:grid;gap:30px;margin-top:22px}.seat-status{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:14px}.seat-status>div{background:var(--surface-2);border:1px solid var(--line);border-radius:12px;padding:11px}.seat-status small{display:block;color:var(--muted)}.seat-status b{font-size:19px}.seat-empty{padding:80px 20px;text-align:center;color:var(--muted);border:2px dashed var(--line);border-radius:18px;background:var(--surface)}
    @media(max-width:1100px){.seat-layout{grid-template-columns:1fr}.seat-panel{position:static}}@media(max-width:650px){.seat-form{grid-template-columns:1fr}.seat-form .wide{grid-column:auto}.seat-row{grid-template-columns:72px repeat(4,minmax(60px,1fr));gap:5px}.seat-paper{padding:16px;overflow:auto}.seat-status{grid-template-columns:1fr 1fr}}
    `;document.head.appendChild(st);
  }

  const nav=document.querySelector('.nav');
  if(nav&&!document.querySelector('[data-view="seating"]')){
    const btn=document.createElement('button');btn.className='nav-link';btn.dataset.view='seating';btn.innerHTML='<span>▦</span>Seating Plan';
    const reports=document.querySelector('[data-view="reports"]');nav.insertBefore(btn,reports||null);
    btn.addEventListener('click',()=>{ if(typeof navigate==='function') navigate('seating'); else showSeatView(); refreshSeatStats(); });
  }

  const content=document.querySelector('.content');
  if(content&&!document.getElementById('seating')){
    const view=document.createElement('section');view.className='view';view.id='seating';
    view.innerHTML=`
      <div class="section-toolbar"><div><h3>Seating Plan</h3><p>Generate room-wise seating in the Ashoka examination format and export to PDF or Excel.</p></div><div class="button-row"><button class="btn btn-outline" id="seatExportExcel">Export Excel</button><button class="btn btn-primary" id="seatExportPdf">Export PDF</button></div></div>
      <div class="seat-layout">
        <div class="card seat-panel">
          <h3>Plan Details</h3>
          <div class="seat-form">
            <label class="wide">College Name<input class="input" id="seatCollege" value="ASHOKA WOMEN'S ENGINEERING COLLEGE - 2T"></label>
            <label>Date of Examination<input class="input" id="seatDate" type="date" value="2026-08-24"></label>
            <label>Room Number(s)<input class="input" id="seatRooms" placeholder="e.g. 101, 102"></label>
            <label class="wide">Year & Semester<input class="input" id="seatYearSem" value="III B. Tech Year I Semester (R23) MID - I Examinations August- 2026"></label>
            <label class="wide">Name of Subject(s)<input class="input" id="seatSubjects" value="ADICA,MM,WRE & PE"></label>
            <label>Room Capacity<select class="input" id="seatCapacity"><option>24</option><option>32</option><option>40</option><option selected>48</option><option>56</option><option>64</option></select></label>
            <label>Columns per Hall Row<input class="input" value="4" disabled></label>
            <label class="wide">Hall No. A — Load from Student Master<div class="seat-source"><select class="input" id="seatBranchA"><option value="">Choose branch</option><option value="ALL">All Active Students</option><option>CIVIL</option><option>CSE</option><option>ECE</option><option>EEE</option><option>MECH</option></select><button class="btn btn-outline" type="button" id="seatLoadA">Load A</button></div></label>
            <label class="wide">Hall No. A Hall Tickets<textarea class="input seat-textarea" id="seatHallA" placeholder="One hall ticket per line, or separate by comma / space"></textarea></label>
            <label class="wide">Hall No. B — Load from Student Master<div class="seat-source"><select class="input" id="seatBranchB"><option value="">Choose branch</option><option value="ALL">All Active Students</option><option>CIVIL</option><option>CSE</option><option>ECE</option><option>EEE</option><option>MECH</option></select><button class="btn btn-outline" type="button" id="seatLoadB">Load B</button></div></label>
            <label class="wide">Hall No. B Hall Tickets<textarea class="input seat-textarea" id="seatHallB" placeholder="One hall ticket per line, or separate by comma / space"></textarea></label>
          </div>
          <div class="seat-actions"><button class="btn btn-primary" type="button" id="seatGenerate">Generate Seating Plan</button><button class="btn btn-outline" type="button" id="seatAutoSplit">Auto Split Active Students</button><button class="btn btn-outline" type="button" id="seatClear">Clear</button></div>
          <p class="seat-help">The 48-seat format allocates up to 24 candidates to Hall No. A and 24 to Hall No. B per room, displayed as 4 boxed hall tickets per line, matching the attached layout.</p>
        </div>
        <div><div class="seat-status" id="seatStatus"><div><small>Hall A</small><b>0</b></div><div><small>Hall B</small><b>0</b></div><div><small>Total</small><b>0</b></div><div><small>Rooms</small><b>0</b></div></div><div class="seat-preview-wrap" id="seatPreview"><div class="seat-empty">Enter or load Hall No. A / Hall No. B candidates and click <b>Generate Seating Plan</b>.</div></div></div>
      </div>`;
    content.appendChild(view);
  }

  let plans=[];const absentByRoom={};
  function appState(){try{return JSON.parse(localStorage.getItem('campusExamData_v1'))||{students:[]}}catch{return{students:[]}}}
  function notify(m){if(typeof toast==='function')toast(m);else alert(m)}
  function escSeat(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
  function tickets(v){return [...new Set(String(v||'').trim().split(/[\s,;]+/).map(x=>x.trim().toUpperCase()).filter(Boolean))]}
  function fmtDate(v){if(!v)return'';const [y,m,d]=v.split('-');return `${d}.${m}.${y}`}
  function safeSheetName(v,i){return (String(v||`Room ${i+1}`).replace(/[\\/?*\[\]:]/g,'-').slice(0,31)||`Room ${i+1}`)}
  function loadBranch(target,select){const branch=document.getElementById(select).value;if(!branch){notify('Choose a branch first');return}const s=appState().students||[];const list=s.filter(x=>(x.status||'Active')==='Active'&&(branch==='ALL'||x.branch===branch)).sort((a,b)=>String(a.hall).localeCompare(String(b.hall))).map(x=>x.hall);document.getElementById(target).value=list.join('\n');refreshSeatStats();notify(`${list.length} students loaded`)}
  function refreshSeatStats(){const a=tickets(document.getElementById('seatHallA')?.value),b=tickets(document.getElementById('seatHallB')?.value);const cap=Number(document.getElementById('seatCapacity')?.value||48),half=Math.floor(cap/2),rooms=Math.max(1,Math.ceil(Math.max(a.length,b.length)/Math.max(half,1)));const boxes=document.querySelectorAll('#seatStatus b');if(boxes.length===4){boxes[0].textContent=a.length;boxes[1].textContent=b.length;boxes[2].textContent=a.length+b.length;boxes[3].textContent=(a.length+b.length)?rooms:0}}
  function buildPlans(){let a=tickets(document.getElementById('seatHallA').value),b=tickets(document.getElementById('seatHallB').value);if(!a.length&&!b.length){notify('Add or load Hall No. A / Hall No. B candidates');return []}const setA=new Set(a);const dups=b.filter(x=>setA.has(x));if(dups.length){b=b.filter(x=>!setA.has(x));document.getElementById('seatHallB').value=b.join('\n');notify(`${dups.length} duplicate hall ticket(s) removed from Hall No. B`)}const cap=Number(document.getElementById('seatCapacity').value||48),per=Math.floor(cap/2),roomInput=document.getElementById('seatRooms').value.split(',').map(x=>x.trim()).filter(Boolean);const needed=Math.max(1,Math.ceil(Math.max(a.length,b.length)/per),roomInput.length);const out=[];for(let i=0;i<needed;i++){const room=roomInput[i]||(needed===1?'':`Room ${i+1}`);out.push({room,a:a.slice(i*per,(i+1)*per),b:b.slice(i*per,(i+1)*per),capacity:cap})}return out}
  function meta(){return{college:document.getElementById('seatCollege').value.trim(),date:document.getElementById('seatDate').value,yearSem:document.getElementById('seatYearSem').value.trim(),subjects:document.getElementById('seatSubjects').value.trim()}}
  function seatRows(plan){const rows=Math.max(Math.ceil(plan.a.length/4),Math.ceil(plan.b.length/4),Math.ceil((plan.capacity/2)/4));const out=[];for(let r=0;r<rows;r++)out.push({a:plan.a.slice(r*4,r*4+4),b:plan.b.slice(r*4,r*4+4)});return out}
  function render(){plans=buildPlans();if(!plans.length)return;const m=meta();const wrap=document.getElementById('seatPreview');wrap.innerHTML=plans.map((p,idx)=>{const rows=seatRows(p),registered=p.a.length+p.b.length,abs=Number(absentByRoom[idx]||0),present=Math.max(0,registered-abs);return `<article class="seat-paper" data-seat-room="${idx}"><h2 class="seat-paper-title">${escSeat(m.college)}</h2><table class="seat-meta"><tr><td>Date of Examination:</td><td>${escSeat(fmtDate(m.date))}</td></tr><tr><td>Year & Semester:</td><td>${escSeat(m.yearSem)}</td></tr><tr><td>Name of the Subject(s):</td><td>${escSeat(m.subjects)}</td></tr></table><div class="seat-plan-title">Seating Plan</div><div class="seat-room">Room Number <div class="seat-room-box">${escSeat(p.room)}</div></div><div class="seat-grid">${rows.map(r=>`<div class="seat-row"><div class="seat-row-label">Hall No. A <span>⇒</span></div>${[0,1,2,3].map(i=>`<div class="seat-box">${escSeat(r.a[i]||'')}</div>`).join('')}</div><div class="seat-row"><div class="seat-row-label">Hall No. B <span>⇒</span></div>${[0,1,2,3].map(i=>`<div class="seat-box">${escSeat(r.b[i]||'')}</div>`).join('')}</div>`).join('')}</div><div class="seat-counts"><div class="seat-count-line"><div>Number of Candidates Registered:</div><div>${registered}</div></div><div class="seat-count-line"><div>Number of Candidates Absent:</div><div><input type="number" min="0" max="${registered}" value="${abs}" data-seat-absent="${idx}"></div></div><div class="seat-count-line"><div>Number of Candidates Present:</div><div data-seat-present="${idx}">${present}</div></div></div><div class="seat-sign">Signature of the Invigilator(s)<div class="seat-sign-numbers"><span>1</span><span>2</span></div></div></article>`}).join('');wrap.querySelectorAll('[data-seat-absent]').forEach(inp=>inp.addEventListener('input',()=>{const i=Number(inp.dataset.seatAbsent),reg=plans[i].a.length+plans[i].b.length,v=Math.max(0,Math.min(reg,Number(inp.value||0)));absentByRoom[i]=v;const p=wrap.querySelector(`[data-seat-present="${i}"]`);if(p)p.textContent=reg-v}));refreshSeatStats();notify(`${plans.length} seating plan${plans.length===1?'':'s'} generated`)}

  async function loadScript(src,test){if(test())return;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
  async function ensurePdf(){await loadScript('https://cdn.jsdelivr.net/npm/jspdf@2.5.1/dist/jspdf.umd.min.js',()=>!!window.jspdf?.jsPDF)}
  async function ensureXlsx(){await loadScript('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js',()=>!!window.XLSX)}
  function getAbsent(i){const el=document.querySelector(`[data-seat-absent="${i}"]`);return Math.max(0,Number(el?.value||0))}

  async function exportPdf(){if(!plans.length){render();if(!plans.length)return}try{await ensurePdf();const {jsPDF}=window.jspdf;const doc=new jsPDF({orientation:'portrait',unit:'mm',format:'a4'}),m=meta();plans.forEach((p,idx)=>{if(idx)doc.addPage();doc.setTextColor(0);doc.setFont('helvetica','bold');doc.setFontSize(14);doc.text(m.college||'ASHOKA WOMEN\'S ENGINEERING COLLEGE - 2T',105,14,{align:'center'});const x=10,y=25,w=190,labelW=47,rowH=8;doc.setLineWidth(.25);for(let r=0;r<3;r++){doc.rect(x,y+r*rowH,w,rowH);doc.line(x+labelW,y+r*rowH,x+labelW,y+(r+1)*rowH)}doc.setFontSize(8.5);doc.setFont('helvetica','bold');doc.text('Date of Examination:',x+2,y+5.3);doc.text('Year & Semester:',x+2,y+rowH+5.3);doc.text('Name of the Subject(s):',x+2,y+rowH*2+5.3);doc.setFont('helvetica','normal');doc.text(fmtDate(m.date),x+labelW+2,y+5.3);doc.setFontSize(7.6);doc.text(doc.splitTextToSize(m.yearSem,138),x+labelW+2,y+rowH+4.8);doc.text(doc.splitTextToSize(m.subjects,138),x+labelW+2,y+rowH*2+4.8);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('Seating Plan',105,55,{align:'center'});doc.setFontSize(8.5);doc.text('Room Number',16,70);doc.rect(48,64,18,9);doc.setFont('helvetica','normal');doc.text(String(p.room||''),57,70,{align:'center'});const rows=seatRows(p),startY=88,labelX=15,boxX=[54,88,122,156],boxW=30,boxH=7,gap=3.3;let cy=startY;doc.setFontSize(7);rows.forEach(r=>{doc.setFont('helvetica','bold');doc.text('Hall No. A   =>',labelX,cy+4.8);doc.setFont('helvetica','normal');for(let i=0;i<4;i++){doc.rect(boxX[i],cy,boxW,boxH);const t=r.a[i]||'';doc.text(t,boxX[i]+boxW/2,cy+4.6,{align:'center'})}cy+=boxH+gap;doc.setFont('helvetica','bold');doc.text('Hall No. B   =>',labelX,cy+4.8);doc.setFont('helvetica','normal');for(let i=0;i<4;i++){doc.rect(boxX[i],cy,boxW,boxH);const t=r.b[i]||'';doc.text(t,boxX[i]+boxW/2,cy+4.6,{align:'center'})}cy+=boxH+5.2});const registered=p.a.length+p.b.length,abs=getAbsent(idx),present=Math.max(0,registered-abs),countY=Math.max(218,cy+25);doc.setFontSize(9);doc.setFont('helvetica','normal');const lx=94,bx=96,bw=18,bh=9;doc.text('Number of Candidates Registered:',lx,countY+6,{align:'right'});doc.rect(bx,countY,bw,bh);doc.text(String(registered),bx+bw/2,countY+6,{align:'center'});doc.text('Number of Candidates Absent:',lx,countY+15,{align:'right'});doc.rect(bx,countY+9,bw,bh);doc.text(String(abs||''),bx+bw/2,countY+15,{align:'center'});doc.text('Number of Candidates Present:',lx,countY+24,{align:'right'});doc.rect(bx,countY+18,bw,bh);doc.text(String(present),bx+bw/2,countY+24,{align:'center'});doc.setFontSize(9.5);doc.text('Signature of the Invigilator(s)',10,268);doc.text('1',82,280);doc.text('2',82,292)});const name=`Seating_Plan_${m.date||'Exam'}.pdf`;doc.save(name);notify('PDF exported')}catch(e){console.error(e);notify('Could not export PDF. Check your internet connection and try again.')}}

  async function exportExcel(){if(!plans.length){render();if(!plans.length)return}try{await ensureXlsx();const wb=XLSX.utils.book_new(),m=meta();plans.forEach((p,idx)=>{const rows=[[m.college],['Date of Examination:',fmtDate(m.date)],['Year & Semester:',m.yearSem],['Name of the Subject(s):',m.subjects],[],['Seating Plan'],['Room Number',p.room],[]];seatRows(p).forEach(r=>{rows.push(['Hall No. A =>',...(r.a.concat(['','','','']).slice(0,4))]);rows.push(['Hall No. B =>',...(r.b.concat(['','','','']).slice(0,4))])});const reg=p.a.length+p.b.length,abs=getAbsent(idx);rows.push([],['Number of Candidates Registered:',reg],['Number of Candidates Absent:',abs||''],['Number of Candidates Present:',Math.max(0,reg-abs)],[],['Signature of the Invigilator(s)'],['1'],['2']);const ws=XLSX.utils.aoa_to_sheet(rows);ws['!cols']=[{wch:32},{wch:20},{wch:20},{wch:20},{wch:20}];ws['!merges']=[{s:{r:0,c:0},e:{r:0,c:4}},{s:{r:5,c:0},e:{r:5,c:4}}];XLSX.utils.book_append_sheet(wb,ws,safeSheetName(p.room,idx))});XLSX.writeFile(wb,`Seating_Plan_${m.date||'Exam'}.xlsx`);notify('Excel file exported')}catch(e){console.error(e);notify('Could not export Excel. Check your internet connection and try again.')}}

  function showSeatView(){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='seating'));document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view==='seating'));const t=document.getElementById('pageTitle');if(t)t.textContent='Seating Plan'}
  document.getElementById('seatLoadA')?.addEventListener('click',()=>loadBranch('seatHallA','seatBranchA'));
  document.getElementById('seatLoadB')?.addEventListener('click',()=>loadBranch('seatHallB','seatBranchB'));
  document.getElementById('seatGenerate')?.addEventListener('click',render);
  document.getElementById('seatExportPdf')?.addEventListener('click',exportPdf);
  document.getElementById('seatExportExcel')?.addEventListener('click',exportExcel);
  document.getElementById('seatAutoSplit')?.addEventListener('click',()=>{const list=(appState().students||[]).filter(x=>(x.status||'Active')==='Active').sort((a,b)=>String(a.hall).localeCompare(String(b.hall))).map(x=>String(x.hall).toUpperCase());document.getElementById('seatHallA').value=list.filter((_,i)=>i%2===0).join('\n');document.getElementById('seatHallB').value=list.filter((_,i)=>i%2===1).join('\n');refreshSeatStats();notify(`${list.length} active students split between Hall A and Hall B`)});
  document.getElementById('seatClear')?.addEventListener('click',()=>{document.getElementById('seatHallA').value='';document.getElementById('seatHallB').value='';document.getElementById('seatRooms').value='';plans=[];document.getElementById('seatPreview').innerHTML='<div class="seat-empty">Enter or load Hall No. A / Hall No. B candidates and click <b>Generate Seating Plan</b>.</div>';refreshSeatStats()});
  ['seatHallA','seatHallB','seatCapacity'].forEach(id=>document.getElementById(id)?.addEventListener('input',refreshSeatStats));

  const quick=document.querySelector('#dashboard .quick-grid');if(quick&&!document.getElementById('seatQuickAction')){const q=document.createElement('button');q.className='quick-action';q.id='seatQuickAction';q.innerHTML='<span>▦</span><b>Seating Plan</b><small>Room-wise seating & export</small>';q.addEventListener('click',()=>{if(typeof navigate==='function')navigate('seating');else showSeatView()});quick.appendChild(q)}
  refreshSeatStats();
})();